-- MySQL Script generated by MySQL Workbench
-- Sun Nov 27 18:37:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PiV2` DEFAULT CHARACTER SET utf8 ;
USE `PiV2` ;

-- -----------------------------------------------------
-- Table `mydb`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PiV2`.`Candidato` (
  `idCandidato` INT NOT NULL AUTO_INCREMENT,
  `nomeCandidato` VARCHAR(100) NOT NULL,
  `nomeVice` VARCHAR(45) NOT NULL,
  `siglaPartido` VARCHAR(10) NOT NULL,
  `numeroPartido` INT(2) NOT NULL,
  PRIMARY KEY (`idCandidato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PiV2`.`Pesquisa` (
  `idPesquisa` INT NOT NULL AUTO_INCREMENT,
  `UF` VARCHAR(2) NOT NULL,
  `data` DATE NOT NULL,
  `fonte` VARCHAR(200) NOT NULL,
  `porcentagem` FLOAT NOT NULL,
  `Candidato_idCandidato` INT NOT NULL,
  PRIMARY KEY (`idPesquisa`, `Candidato_idCandidato`),
  INDEX `fk_Pesquisa_Candidato_idx` (`Candidato_idCandidato` ASC) VISIBLE,
  CONSTRAINT `fk_Pesquisa_Candidato`
    FOREIGN KEY (`Candidato_idCandidato`)
    REFERENCES `PiV2`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
